AppBundle\Entity\SeriesAuthorRole:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        author:
            targetEntity: Author
            joinColumn:
                nullable: false
        role:
            targetEntity: Role
            joinColumn:
                nullable: true
        series:
            targetEntity: Series
            joinColumn:
                nullable: false
    lifecycleCallbacks: {}
