AppBundle\Entity\VideoSeriesEpisode:
    type: entity
    table: null
    fields:
        order:
            type: smallint
        duration:
            type: integer
    manyToOne:
        season:
            targetEntity: VideoSeriesSeason
            joinColumn:
                nullable: false
    lifecycleCallbacks: {}
