AppBundle\Entity\VideoSeriesSeason:
    type: entity
    table: null
    fields:
        order:
            type: smallint
        count:
            type: smallint
    oneToMany:
        episodes:
            targetEntity: VideoSeriesEpisode
            mappedBy: season
    lifecycleCallbacks: {}
